###服务名称(服务注册到eureka名称)
spring:
  application:
    name: app-jckc-zuul
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka
## 配置网关反向代理
zuul:
  routes:
    api-a:
      path: /wx/**
      serviceId: app-jckc-weixin
    api-b:
      path: /member/**
      serviceId: app-jckc-member
